---
kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
namespace: apps
resources:
  - secrets.yml
  - deployment.yml
  - service.yml
  - ingress.yml
configMapGenerator:
  - name: repo-social-config
    namespace: apps
    literals:
      - QUARKUS_NEO4J_AUTHENTICATION_URI=bolt://neo4j.neo4j.svc.cluster.local
