apiVersion: batch/v1
kind: Job
metadata:
  name: redis-cluster
  namespace: redis
spec:
  template:
    spec:
      initContainers:
        - name: init
          image: redis:8.0-M04-alpine3.21
          command: ["sh", "-c"]
          args:
            - |
              for i in 0 1 2; do
                until redis-cli -a admin -h redis-$i.redis.redis.svc.cluster.local ping; do
                  echo "Waiting for redis-$i to be ready..."
                  sleep 5
                done
              done
      containers:
        - name: redis
          image: redis:8.0-M04-alpine3.21
          command: ["sh", "-c"]
          args:
            - |
              # Check if redis-0 is already clustered
              IS_CLUSTERED=$(redis-cli -a admin -h redis-0.redis.redis.svc.cluster.local cluster info 2>/dev/null | grep cluster_state:ok || true)
              if [ -n "$IS_CLUSTERED" ]; then
                echo "Redis cluster is already created. Skipping."
              else
                echo "Creating Redis cluster..."
                redis-cli --cluster create \
                  redis-0.redis.redis.svc.cluster.local:6379 \
                  redis-1.redis.redis.svc.cluster.local:6379 \
                  redis-2.redis.redis.svc.cluster.local:6379 \
                  --cluster-replicas 0 \
                  -a admin \
                  --cluster-yes
              fi
      restartPolicy: OnFailure
  backoffLimit: 4
  ttlSecondsAfterFinished: 60
  activeDeadlineSeconds: 300
