---
kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
namespace: redis
resources:
  - namespace.yml
  - deployment.yml
  - service.yml
  - secrets.yml
configMapGenerator:
  - name: redis-config
    namespace: redis
    literals:
      - |-
        redis.conf=port 6379
        appendonly yes
        protected-mode no
        bind 0.0.0.0
