apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  namespace: redis
spec:
  serviceName: redis
  replicas: 3
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:8.0-M04-alpine3.21
          command: ["redis-server", "/conf/redis.conf"]
          resources:
            requests:
              memory: "256Mi"
              cpu: "125m"
            limits:
              memory: "512Mi"
              cpu: "250m"
          ports:
            - containerPort: 6379
          volumeMounts:
            - name: redis-config
              mountPath: /conf
          livenessProbe: # TODO admin should be secret
            exec:
              command:
                - redis-cli
                - -a
                - admin
                - ping
            initialDelaySeconds: 15
            periodSeconds: 10
            failureThreshold: 3
          readinessProbe:
            exec:
              command: # TODO admin should be secret
                - redis-cli
                - -a
                - admin
                - ping
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 3
      volumes:
        - name: redis-config
          secret:
            secretName: redis-secret
