services:
  redis:
    image: redis:8.0-M04-alpine3.21
    container_name: redis
    command: redis-server --requirepass admin
    ports:
      - "6379:6379"
    expose:
      - "6379"

  redisinsight:
    image: redislabs/redisinsight:2.66
    container_name: redisinsight
    ports:
      - "5540:5540"
    environment:
      - REDISINSIGHT_PASSWORD=admin
    depends_on:
      - redis
    expose:
      - "5540"

  neo4j:
    image: neo4j:5.18
    container_name: neo4j
    restart: unless-stopped
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: neo4j/password
