---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo-config
  namespace: mongo
spec:
  serviceName: "mongo-config"
  replicas: 3
  selector:
    matchLabels:
      role: config
  template:
    metadata:
      labels:
        role: config
    spec:
      containers:
        - name: mongo-config
          image: mongo:6.0
          command: ["mongod", "--configsvr", "--replSet", "cfgReplicaSet", "--port", "27017", "--bind_ip", "0.0.0.0"]
          volumeMounts:
            - name: mongo-data
              mountPath: /data/db
      volumes:
        - name: mongo-data
          persistentVolumeClaim:
            claimName: mongo-config-pvc
