apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongos
  namespace: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongos
  template:
    metadata:
      labels:
        app: mongos
    spec:
      containers:
        - name: mongos
          image: mongo:8.0.6
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 27017
          command: [
            "/bin/sh",
            "-c",
            "mongos --configdb configReplSet/mongo-config-0.mongo-config.mongo.svc.cluster.local:27019,mongo-config-1.mongo-config.mongo.svc.cluster.local:27019 --bind_ip 0.0.0.0"
          ]
          resources:
            requests:
              cpu: "125m"
              memory: "256Mi"
            limits:
              cpu: "250m"
              memory: "512Mi"
          livenessProbe:
            exec:
              command: ["/bin/sh", "-c", "mongosh --quiet --eval 'db.runCommand({ping: 1})'"]
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 10
            failureThreshold: 3
          readinessProbe:
            exec:
              command: ["/bin/sh", "-c", "mongosh --quiet --eval 'db.runCommand({ping: 1})'"]
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 10
            failureThreshold: 5
          volumeMounts:
            - name: mongos-init
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: mongos-init
          configMap:
            name: mongos-init
