---
apiVersion: v1
kind: Service
metadata:
  name: mongos
  namespace: mongo
spec:
  type: ClusterIP
  selector:
    app: mongos
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
