apiVersion: apps/v1
kind: Deployment
metadata:
  name: repo-user
  namespace: apps
  labels:
    app: repo-user
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: repo-user
  template:
    metadata:
      labels:
        app: repo-user
    spec:
      imagePullSecrets:
        - name: pull-secret
      containers:
        - name: repo-user
          image: registry.cri.epita.fr/ing/majeures/tc/info/student/2026/2025-epitweet-tinyx-02/repo-user:07c2dc43bd47413cfa18b53dbe7faffa46e6e795 # TODO: use explicit tag
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "256Mi"
              cpu: "125m"
            limits:
              memory: "512Mi"
              cpu: "250m"
          livenessProbe:
            httpGet:
              path: /q/health/live
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /q/health/ready
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          env:
            - name: REPO_USER_QUARKUS_HTTP_PORT
              value: "8080"
            - name: REPO_USER_REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: repo-user-config
                  key: REPO_USER_REDIS_HOST
            - name: REPO_USER_REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: repo-user-secret
                  key: REPO_USER_REDIS_PASSWORD
            - name: REPO_USER_AGGREGATE_CHANNEL
              valueFrom:
                configMapKeyRef:
                  name: apps-config
                  key: USER_AGGREGATE_CHANNEL
            - name: REPO_USER_MONGODB_HOST
              valueFrom:
                configMapKeyRef:
                  name: repo-user-config
                  key: REPO_USER_MONGODB_HOST
            - name: REPO_USER_APP_PROFILE
              valueFrom:
                configMapKeyRef:
                  name: apps-config
                  key: USER_APP_PROFILE
            - name: REPO_USER_MINIO_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: repo-user-config
                  key: REPO_USER_MINIO_ENDPOINT
            - name: REPO_USER_MINIO_BUCKET
              value: "RepoUser"
            - name: REPO_USER_MINIO_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: repo-user-secret
                  key: REPO_USER_MINIO_ACCESS_KEY
            - name: REPO_USER_MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: repo-user-secret
                  key: REPO_USER_MINIO_SECRET_KEY
            - name: REPO_USER_MONGODB_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: repo-user-config
                  key: REPO_USER_MONGODB_DATABASE
