apiVersion: apps/v1
kind: Deployment
metadata:
  name: repo-user
  namespace: apps
  labels:
    app: repo-user
spec:
  replicas: 1 # TODO: make it 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: repo-user
  template:
    metadata:
      labels:
        app: repo-user
    spec:
      imagePullSecrets:
        - name: pull-secret
      containers:
        - name: repo-user
          image: registry.cri.epita.fr/ing/majeures/tc/info/student/2026/2025-epitweet-tinyx-02/repo-user:v1.0.14
          imagePullPolicy: IfNotPresent
          #command: ["tail", "-f", "/dev/null"]
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /q/health/live
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /q/health/ready
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 5
          env:
            ## QUARKUS
            - name: QUARKUS_LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: apps-config
                  key: LOG_LEVEL
            - name: QUARKUS_HTTP_PORT
              valueFrom:
                configMapKeyRef:
                  name: apps-config
                  key: QUARKUS_HTTP_PORT
            - name: QUARKUS_HTTP_HOST
              valueFrom:
                configMapKeyRef:
                  name: apps-config
                  key: QUARKUS_HTTP_HOST
            - name: REPO_USER_APP_PROFILE
              valueFrom:
                configMapKeyRef:
                  name: apps-config
                  key: USER_APP_PROFILE
            ## REDIS
            - name: QUARKUS_REDIS_HOSTS
              valueFrom:
                configMapKeyRef:
                  name: repo-user-config
                  key: REPO_USER_REDIS_HOSTS
            - name: QUARKUS_REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: repo-user-secret
                  key: REPO_USER_REDIS_PASSWORD
            - name: REPO_USER_AGGREGATE_CHANNEL
              valueFrom:
                configMapKeyRef:
                  name: apps-config
                  key: USER_AGGREGATE_CHANNEL
            - name: QUARKUS_REDIS_CLIENT_TYPE
              value: "cluster"
            - name: QUARKUS_REDIS_RECONNECT_ATTEMPTS
              value: "3"
            - name: QUARKUS_REDIS_AUTO_FAILOVER
              value: "true"
            ## MONGODB
            - name: QUARKUS_MONGODB_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: repo-user-secret
                  key: REPO_USER_MONGODB_ENDPOINT
            ## MINIO
            - name: REPO_USER_MINIO_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: repo-user-config
                  key: REPO_USER_MINIO_ENDPOINT
            - name: REPO_USER_MINIO_BUCKET
              valueFrom:
                configMapKeyRef:
                  name: repo-user-config
                  key: REPO_USER_MINIO_BUCKET
            - name: REPO_USER_MINIO_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: repo-user-secret
                  key: REPO_USER_MINIO_ACCESS_KEY
            - name: REPO_USER_MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: repo-user-secret
                  key: REPO_USER_MINIO_SECRET_KEY
