---
kind: Secret
apiVersion: v1
metadata:
  name: repo-user-secret
  namespace: apps
type: Opaque
stringData:
  REPO_USER_REDIS_USERNAME: "your_redis_user"
  REPO_USER_REDIS_PASSWORD: "your_redis_password" # Replace with your actual Redis password
  REPO_USER_MINIO_ACCESS_KEY: "your_minio_access_key" # Replace with your actual MinIO access key
  REPO_USER_MINIO_SECRET_KEY: "your_minio_secret_key" # Replace with your actual MinIO secret key
  REPO_USER_MONGODB_USERNAME: "your_mongo_username"
  REPO_USER_MONGODB_PASSWORD: "your mongo password"
