---
kind: Secret
apiVersion: v1
metadata:
  name: repo-user-secret
  namespace: apps
type: Opaque
stringData:
  REPO_USER_REDIS_USERNAME: "default"
  REPO_USER_REDIS_PASSWORD: "admin"
  REPO_USER_MINIO_ACCESS_KEY: "minio"
  REPO_USER_MINIO_SECRET_KEY: "miniosecret"
  REPO_USER_MONGODB_ENDPOINT: "mongodb://admin:admin@mongos.mongo.svc.cluster.local:27017/RepoUser?authSource=RepoUser&w=majority"

