kind: Service
apiVersion: v1
metadata:
  name: neo4j
  namespace: neo4j
  labels:
    app: neo4j
spec:
  type: ClusterIP
  ports:
    - name: neo4j
      port: 7474
      targetPort: 7474
    - name: bolt
      port: 7687
      targetPort: 7687
  selector:
    app: neo4j
