---
kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
resources:
  - namespace.yml
  - elasticsearch.yml
  - service.yml
  - secret.yml
  - statefulset.yml

ConfigMapGenerator:
  - name: elasticsearch-config
    namespace: elastic
    literals:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
