apiVersion: v1
kind: Service
metadata:
  name: minio
  namespace: minio-b
spec:
  selector:
    app: minio
  ports:
    - name: api
      protocol: TCP
      port: 9001
      targetPort: 9000
    - name: console
      protocol: TCP
      port: 36338
      targetPort: 36337
  type: ClusterIP