
apiVersion: apps/v1
kind: Deployment
metadata:
  name: srvc-search
  namespace: apps
  labels:
    app: srvc-search
spec:
  replicas: 1 # Number of replicas
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: srvc-search
  template:
    metadata:
      labels:
        app: srvc-search
    spec:
      imagePullSecrets:
        - name: pull-secret
      containers:
        - name: srvc-search
          image: registry.cri.epita.fr/ing/majeures/tc/info/student/2026/2025-epitweet-tinyx-02/srvc-search:v1.0.1
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /q/health/live
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /q/health/ready
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10
          env:
            ## QUARKUS
            - name: QUARKUS_LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: apps-config
                  key: QUARKUS_LOG_LEVEL
            - name: QUARKUS_HTTP_PORT
              valueFrom:
                configMapKeyRef:
                  name: apps-config
                  key: QUARKUS_HTTP_PORT
            - name: QUARKUS_HTTP_HOST
              valueFrom:
                configMapKeyRef:
                  name: apps-config
                  key: QUARKUS_HTTP_HOST
            - name: QUARKUS_APP_PROFILE
              valueFrom:
                configMapKeyRef:
                  name: apps-config
                  key: QUARKUS_APP_PROFILE
            
                  
            ## REDIS
            - name: QUARKUS_REDIS_HOSTS
              valueFrom:
                configMapKeyRef:
                  name: apps-config
                  key: QUARKUS_REDIS_HOSTS
            - name: QUARKUS_REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: apps-secret
                  key: QUARKUS_REDIS_PASSWORD
            - name: QUARKUS_REDIS_CLIENT_TYPE
              valueFrom:
                configMapKeyRef:
                  name: apps-config
                  key: QUARKUS_REDIS_CLIENT_TYPE
            - name: QUARKUS_REDIS_RECONNECT_ATTEMPTS
              valueFrom:
                configMapKeyRef:
                  name: apps-config
                  key: QUARKUS_REDIS_RECONNECT_ATTEMPTS
            - name: QUARKUS_REDIS_AUTO_FAILOVER
              valueFrom:
                configMapKeyRef:
                  name: apps-config
                  key: QUARKUS_REDIS_AUTO_FAILOVER
            - name: POST_AGGREGATE_CHANNEL
              valueFrom:
                configMapKeyRef:
                  name: apps-config
                  key: POST_AGGREGATE_CHANNEL 
            - name: BLOCK_COMMAND_CHANNEL
              valueFrom:
                configMapKeyRef:
                  name: apps-config
                  key: BLOCK_COMMAND_CHANNEL
                 

            ## MONGODB
            - name: QUARKUS_MONGODB_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: repo-user-secret
                  key: REPO_USER_MONGODB_ENDPOINT

            ## ELASTIC SEARCH
            - name: QUARKUS_ELASTICSEARCH_HOSTS
              valueFrom:
                configMapKeyRef:
                  name: srvc-search-config
                  key: ELASTICSEARCH_HOSTS
            - name: ELASTIC_INDEX
              valueFrom:
                configMapKeyRef:
                  name: srvc-search-config
                  key: ELASTICSEARCH_INDEX
            - name: QUARKUS_ELASTICSEARCH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: srvc-search-secret
                  key: ELASTIC_SEARCH_PASSWORD
            - name: QUARKUS_ELASTICSEARCH_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: srvc-search-config
                  key: ELASTICSEARCH_USERNAME
            - name: QUARKUS_ELASTICSEARCH_PORT
              valueFrom:
                configMapKeyRef:
                  name: srvc-search-config
                  key: ELASTICSEARCH_PORT
