---
kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
namespace: apps
resources:
  - secrets.yml
  - deployment.yml
  - service.yml
  - ingress.yml
configMapGenerator:
  - name: srvc-search-config
    namespace: apps
    literals:
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_HOSTS=elasticsearch-client.elastic.svc.cluster.local:9200
      - ELASTICSEARCH_PORT=9200
      - ELASTICSEARCH_INDEX=srvc_search
