---
apiVersion: v1
kind: Service
metadata:
  name: mongo-shard
  namespace: mongo
  labels:
    app: mongo-shard
spec:
  type: ClusterIP
  selector:
    app: mongo-shard
  ports:
    - protocol: TCP
      port: 27018
      targetPort: 27018
