kind: Secret
apiVersion: v1
metadata:
  name: srvc-user-timeline-secret
  namespace: apps
type: Opaque
stringData:
  # MONGODB
  SRVC_USER_TIMELINE_MONGODB_ENDPOINT: "mongodb://admin:admin@mongos.mongo.svc.cluster.local:27017/SrvcUserTimeline?authSource=SrvcUserTimeline&w=majority"
