.rules_template:
  script:
    - |
      if [[ "$CI_COMMIT_MESSAGE" =~ $SERVICE_NAME ]] || [[$CI_COMMIT_BRANCH == "main"]] || [[$CI_COMMIT_BRANCH == "dev"]]; then
        echo "Regex matched: Running job"
      else
        echo "Regex did not match: Skipping job"
        exit 0
      fi
