.rules_template_repo-user:
  rules:
    - if: '$CI_COMMIT_BRANCH == "main" || $CI_COMMIT_BRANCH == "dev"'
      when: always
    - if: '$CI_COMMIT_MESSAGE =~ /repo-user/'
      when: always
    - when: never

.rules_template_repo-post:
  rules:
    - if: '$CI_COMMIT_BRANCH == "main" || $CI_COMMIT_BRANCH == "dev"'
      when: always
    - if: '$CI_COMMIT_MESSAGE =~ /repo-post/'
      when: always
    - when: never

.rules_template_repo-social:
  rules:
    - if: '$CI_COMMIT_BRANCH == "main" || $CI_COMMIT_BRANCH == "dev"'
      when: always
    - if: '$CI_COMMIT_MESSAGE =~ /repo-social/'
      when: always
    - when: never

.rules_template_exchange:
  rules:
    - if: '$CI_COMMIT_BRANCH == "main" || $CI_COMMIT_BRANCH == "dev"'
      when: always
    - if: '$CI_COMMIT_MESSAGE =~ /exchange/'
      when: always
    - when: never

.rules_template_srvc-search:
  rules:
    - if: '$CI_COMMIT_BRANCH == "main" || $CI_COMMIT_BRANCH == "dev"'
      when: always
    - if: '$CI_COMMIT_MESSAGE =~ /srvc-search/'
      when: always
    - when: never

.rules_template_srvc-home-timeline:
  rules:
    - if: '$CI_COMMIT_BRANCH == "main" || $CI_COMMIT_BRANCH == "dev"'
      when: always
    - if: '$CI_COMMIT_MESSAGE =~ /srvc-home-timeline/'
      when: always
    - when: never

.rules_template_srvc-user-timeline:
  rules:
    - if: '$CI_COMMIT_BRANCH == "main" || $CI_COMMIT_BRANCH == "dev"'
      when: always
    - if: '$CI_COMMIT_MESSAGE =~ /srvc-user-timeline/'
      when: always
    - when: never
