repo-post:build:
  extends: .rules_template_repo-post
  image:
    name: gcr.io/kaniko-project/executor:v1.23.2-debug
    entrypoint: [""]
  stage: build
  variables:
    DOCKER_REGISTRY: $CI_REGISTRY
    DOCKER_IMAGE: $DOCKER_REGISTRY/repo-post
    DOCKER_TAG: $CI_COMMIT_SHA
  script:
    - echo "{\"auths\":{\"$DOCKER_REGISTRY\":{\"auth\":\"$(echo -n ${CI_REGISTRY_USER}:${CI_REGISTRY_PASSWORD} | base64)\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context . --dockerfile Dockerfiles/repo-post.Dockerfile --destination $DOCKER_IMAGE:$DOCKER_TAG

repo-post:lint:
  extends: .rules_template_repo-post
  image: maven:3.8.5-eclipse-temurin-17-alpine
  stage: lint
  script:
    - cd apps/repo-post
    - mvn spotless:check

repo-post:test:
  extends: .rules_template_repo-post
  image: maven:3.8.5-eclipse-temurin-17-alpine
  services:
    - name: "${CI_REGISTRY}/mongodb-repo-post:3.0.0"
      alias: mongo
  variables:
    MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
    MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    MONGO_INITDB_DATABASE: RepoPost
  stage: test
  script:
    - cd apps/
    - mvn install -N && mvn install -pl exchange
    - cd repo-post
    - mvn test
