build-job:
  image:
    name: gcr.io/kaniko-project/executor:v1.23.2-debug
    entrypoint: [""]
  stage: build
  variables:
    DOCKER_REGISTRY: $CI_REGISTRY # TODO: Change this to the Docker registry when created
    DOCKER_IMAGE: $DOCKER_REGISTRY/repo-user
    DOCKER_TAG: $CI_COMMIT_SHA
  before_script:
    - cd apps/repo-user
  script:
    - mvn package -Dquarkus.package.type=uber-jar
    - echo "{\"auths\":{\"$DOCKER_REGISTRY\":{\"auth\":\"$(echo -n ${CI_REGISTRY_USER}:${CI_REGISTRY_PASSWORD} | base64)\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context . --dockerfile Dockerfile --destination $DOCKER_IMAGE:$DOCKER_TAG

lint-job:
  before_script:
    - cd apps/repo-user
  image: eclipse-temurin:17-alpine
  stage: lint
  script:
    - mvn spotless:check
    - mvn spotless:apply

test-job:
  before_script:
    - cd apps/repo-user
  image: eclipse-temurin:17-alpine
  stage: test
  script:
    - mvn test # ADD more configurations here when the tests are ready