repo-user:build:
  extends: .rules_template_repo-user
  image:
    name: gcr.io/kaniko-project/executor:v1.23.2-debug
    entrypoint: [""]
  stage: build
  variables:
    DOCKER_REGISTRY: $CI_REGISTRY
    DOCKER_IMAGE: $DOCKER_REGISTRY/repo-user
    DOCKER_TAG: $CI_COMMIT_SHA
  script:
    - echo "{\"auths\":{\"$DOCKER_REGISTRY\":{\"auth\":\"$(echo -n ${CI_REGISTRY_USER}:${CI_REGISTRY_PASSWORD} | base64)\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context . --dockerfile Dockerfiles/repo-user.Dockerfile --destination $DOCKER_IMAGE:$DOCKER_TAG

repo-user:lint:
  extends: .rules_template_repo-user
  image: maven:3.8.5-eclipse-temurin-17-alpine
  stage: lint
  script:
    - cd apps/repo-user
    - mvn spotless:check

repo-user:test:
  extends: .rules_template_repo-user
  image: maven:3.8.5-eclipse-temurin-17-alpine
  stage: test
  services:
    - name: mongo:8.0.6-noble
      alias: mongo
      command: ["mongod", "--bind_ip_all"]
  script:
    - echo "Running tests..." # TODO: Replace with actual test command
