apiVersion: apps/v1
kind: Deployment
metadata:
  name: srvc-home-timeline
  namespace: apps
  labels:
    app: srvc-home-timeline
spec:
  replicas: 1 # Number of replicas
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: srvc-home-timeline
  template:
    metadata:
      labels:
        app: srvc-home-timeline
    spec:
      imagePullSecrets:
        - name: pull-secret
      containers:
        - name: srvc-home-timeline
          image: registry.cri.epita.fr/ing/majeures/tc/info/student/2026/2025-epitweet-tinyx-02/srvc-home-timeline:v1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /q/health/live
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /q/health/ready
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10
          env:
            ## QUARKUS
            - name: QUARKUS_LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: apps-config
                  key: QUARKUS_LOG_LEVEL
            - name: QUARKUS_HTTP_PORT
              valueFrom:
                configMapKeyRef:
                  name: apps-config
                  key: QUARKUS_HTTP_PORT
            - name: QUARKUS_HTTP_HOST
              valueFrom:
                configMapKeyRef:
                  name: apps-config
                  key: QUARKUS_HTTP_HOST
            - name: QUARKUS_APP_PROFILE
              valueFrom:
                configMapKeyRef:
                  name: apps-config
                  key: QUARKUS_APP_PROFILE
            ## REDIS
            - name: QUARKUS_REDIS_HOSTS
              valueFrom:
                configMapKeyRef:
                  name: apps-config
                  key: QUARKUS_REDIS_HOSTS
            - name: QUARKUS_REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: apps-secret
                  key: QUARKUS_REDIS_PASSWORD
            - name: QUARKUS_REDIS_CLIENT_TYPE
              valueFrom:
                configMapKeyRef:
                  name: apps-config
                  key: QUARKUS_REDIS_CLIENT_TYPE
            - name: QUARKUS_REDIS_RECONNECT_ATTEMPTS
              valueFrom:
                configMapKeyRef:
                  name: apps-config
                  key: QUARKUS_REDIS_RECONNECT_ATTEMPTS
            - name: QUARKUS_REDIS_AUTO_FAILOVER
              valueFrom:
                configMapKeyRef:
                  name: apps-config
                  key: QUARKUS_REDIS_AUTO_FAILOVER
            - name: USER_AGGREGATE_CHANNEL
              valueFrom:
                configMapKeyRef:
                  name: apps-config
                  key: USER_AGGREGATE_CHANNEL
            ## MONGODB
            - name: QUARKUS_MONGODB_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: srvc-home-timeline-secret
                  key: SRVC_HOME_TIMELINE_MONGODB_ENDPOINT
            ## MINIO
            - name: S3_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: apps-config
                  key: S3_ENDPOINT
            - name: S3_BUCKET
              valueFrom:
                configMapKeyRef:
                  name: apps-config
                  key: S3_BUCKET
            - name: S3_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: apps-secret
                  key: S3_ACCESS_KEY
            - name: S3_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: apps-secret
                  key: S3_SECRET_KEY
