services:
  mongo:
    image: mongo:8.0.6-noble
    container_name: mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - ./init.js:/docker-entrypoint-initdb.d/init.js
    ports:
      - 27017:27017
    expose:
      - "27017"

  redis:
    image: redis:8.0-M04-alpine3.21
    container_name: redis
    command: redis-server --requirepass admin
    ports:
      - "6379:6379"
    expose:
      - "6379"

  minio:
    image: quay.io/minio/minio:RELEASE.2025-03-12T18-04-18Z
    container_name: minio
    ports:
      - "9000:9000"
      - "9090:9090"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9090"
    expose:
      - "9000"
      - "9090"

  neo4j:
    image: neo4j:5.18
    container_name: neo4j
    restart: unless-stopped
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: neo4j/password
