---
kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
resources:
  - repo-user
  - repo-social
  - repo-post
  - srvc-search
  - srvc-user-timeline
  - srvc-home-timeline
  - pull-secrets.yml
