---
apiVersion: v1
kind: Secret
metadata:
  name: pull-secret
  namespace: repo-user
stringData:
  .dockerconfigjson: |
    {
      "auths": {
          "registry.cri.epita.fr": {
              "auth": "c2FteS55YWNlZjpiUVdiRmZXYURCcVJUNm94UFA1eA=="
          }
      }
    }
type: kubernetes.io/dockerconfigjson
