kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: repo-post
  namespace: repo-post
  labels:
    app: repo-post
spec:
  rules:
    - http:
        paths: # FIXME: complete paths
          - path: /user
            pathType: Prefix
            backend:
              service:
                name: repo-post
                port:
                  number: 80
          - path: /login
            pathType: Prefix
            backend:
              service:
                name: repo-post
                port:
                  number: 80
