---
kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
namespace: apps
resources:
  - secrets.yml
  - deployment.yml
  - service.yml
  - ingress.yml
configMapGenerator:
  - name: repo-post-config
    namespace: apps
    literals:
      - REPO_POST_MONGODB_HOST=mongos.mongo.svc.cluster.local
      - REPO_POST_REDIS_HOST=redis.redis-0.svc.cluster.local,redis-1.redis.svc.cluster.local
      - REPO_POST_MINIO_ENDPOINT=http://minio.minio.svc.cluster.local:9000
      - REPO_POST_MINIO_BUCKET=RepoPost
      - REPO_POST_MONGODB_DATABASE=RepoPost
      - REPO_POST_APP_PROFILE=prod
