---
kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
namespace: apps
resources:
  - secrets.yml
  - deployment.yml
  - service.yml
  - ingress.yml

configMapGenerator:
  - name: repo-post-config
    namespace: apps
    literals:
      - REPO_POST_REDIS_HOST=mongo-repo-post.mongo-svc.cluster.local
      - REPO_POST_REDIS_PASSWORD=redis.redis-svc.cluster.local
      - REPO_POST_MONGODB_HOST=http://minio-service.minio.svc.cluster.local:9000
      - REPO_POST_APP_PROFILE=prod
      - REPO_POST_MINIO_ACCESS_KEY=minioadmin
      - REPO_POST_MINIO_SECRET_KEY=minioadmin
  # - name: apps-config
  #   namespace: apps
  #   literals:
  #     - USER_AGGREGATE_CHANNEL=user_aggregate
  #     - POST_AGGREGATE_CHANNEL=post_aggregate
  #     - LIKE_COMMAND_CHANNEL=like_command
  #     - BLOCK_COMMAND_CHANNEL=block_command
  #     - FOLLOW_COMMAND_CHANNEL=follow_command
  #     - USER_APP_PROFILE=prod
