---
apiVersion: v1
kind: Service
metadata:
  name: mongo-config
  namespace: mongo
  labels:
    app: mongo-config
spec:
  type: ClusterIP
  selector:
    app: mongo-config
  ports:
    - protocol: TCP
      port: 27019
      targetPort: 27019
